### Title of the Issue
- [ ] **Have you named the issue title clearly and descriptively?**  
<!-- Example: "fix: [Component] Button not responding on click" -->
<!-- Use format: "fix: [affected section] concise description" -->

### Description
<!-- A clear and detailed description of the bug, including what happens, how it happens, and any potential consequences. -->

### Steps to Reproduce
<!-- List out the steps to reproduce the bug, including the code, environment, or any specific conditions. -->

1. Step 1
2. Step 2
3. Step 3

### Expected Behavior
<!-- Describe what you expected to happen. -->

### Actual Behavior
<!-- Describe what actually happened. -->

### Screenshots / Logs
<!-- If applicable, attach screenshots, logs, or any other files to help understand the issue. -->

### Related Issues or Pull Requests
<!-- If this issue is related to other issues or pull requests, mention them here by linking the relevant numbers. -->

### Environment
<!-- Provide details about the environment where the issue was observed (e.g., OS, browser, or framework version). -->

### Checklist
- [ ] I have followed the issue title guidelines.
- [ ] I have included a clear and detailed description.
- [ ] I have provided necessary logs, screenshots, or other files.
